image: docker:git

stages:
#- build
- test
- deploy

services:
- docker:dind

deploy master:
  image: gitlab.services4geeks.co:4567/devops/runner4runer:capistrano
  script:
  - cd config/capistrano
  - cap dev deploy 
  tags:
  - deploy
  only:
  - master
  stage: deploy

